<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Suraj-9693" name="com.qa.TestScripts.DataDrivenTest" tests="7" failures="1" timestamp="13 Apr 2018 09:58:15 GMT" time="68.781" errors="0">
  <testcase name="excelTest" time="2.929" classname="com.qa.TestScripts.DataDrivenTest"/>
  <testcase name="excelTest" time="2.369" classname="com.qa.TestScripts.DataDrivenTest"/>
  <testcase name="excelTest" time="2.806" classname="com.qa.TestScripts.DataDrivenTest"/>
  <testcase name="excelTest" time="2.549" classname="com.qa.TestScripts.DataDrivenTest"/>
  <testcase name="excelTest" time="2.406" classname="com.qa.TestScripts.DataDrivenTest"/>
  <testcase name="afterTest" time="0.670" classname="com.qa.TestScripts.DataDrivenTest">
    <failure type="java.lang.AssertionError" message="Test is not Executed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test is not Executed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.qa.TestScripts.DataDrivenTest.afterTest(DataDrivenTest.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- afterTest -->
  <testcase name="excelTest" time="55.052" classname="com.qa.TestScripts.DataDrivenTest"/>
</testsuite> <!-- com.qa.TestScripts.DataDrivenTest -->
